"""add csv_uploads and prospects tables

Revision ID: 3df82c966685
Revises: 46fb4b7550d6
Create Date: 2026-07-20 01:29:27.441962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3df82c966685'
down_revision: Union[str, Sequence[str], None] = '46fb4b7550d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_uploads_user_id'), 'csv_uploads', ['user_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('csv_upload_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('company_website', sa.String(length=1024), nullable=True),
    sa.Column('facebook_url', sa.String(length=1024), nullable=True),
    sa.Column('twitter_url', sa.String(length=1024), nullable=True),
    sa.Column('research', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matching', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outreach', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESEARCHING', 'MATCHING', 'GENERATING_EMAIL', 'COMPLETED', 'FAILED', name='prospect_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['csv_upload_id'], ['csv_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_csv_upload_id'), 'prospects', ['csv_upload_id'], unique=False)
    op.create_index('ix_prospects_csv_upload_id_status', 'prospects', ['csv_upload_id', 'status'], unique=False)
    op.create_index(op.f('ix_prospects_status'), 'prospects', ['status'], unique=False)
    op.create_index(op.f('ix_prospects_user_id'), 'prospects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospects_user_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_status'), table_name='prospects')
    op.drop_index('ix_prospects_csv_upload_id_status', table_name='prospects')
    op.drop_index(op.f('ix_prospects_csv_upload_id'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_csv_uploads_user_id'), table_name='csv_uploads')
    op.drop_table('csv_uploads')
    # ### end Alembic commands ###
