"""add seller_knowledge and seller_documents tables

Revision ID: d23ee632523a
Revises: 3df82c966685
Create Date: 2026-07-20 02:10:34.734109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd23ee632523a'
down_revision: Union[str, Sequence[str], None] = '3df82c966685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_website', sa.String(length=1024), nullable=True),
    sa.Column('product_website', sa.String(length=1024), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('knowledge_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NOT_GENERATED', 'GENERATING', 'COMPLETED', 'FAILED', name='seller_knowledge_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_knowledge_user_id'), 'seller_knowledge', ['user_id'], unique=True)
    op.create_table('seller_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_knowledge_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_knowledge_id'], ['seller_knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_documents_seller_knowledge_id'), 'seller_documents', ['seller_knowledge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_documents_seller_knowledge_id'), table_name='seller_documents')
    op.drop_table('seller_documents')
    op.drop_index(op.f('ix_seller_knowledge_user_id'), table_name='seller_knowledge')
    op.drop_table('seller_knowledge')
    # ### end Alembic commands ###
